name: expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  gap: ^3.0.1
  get: ^4.6.6
  google_nav_bar: ^5.0.6
  grouped_list: ^5.1.2
  intl: ^0.19.0
  uuid: ^4.4.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
